### ISSUE TITLE
Format the code using black

### ISSUE THREAD

**Issue by za** [state-alchemists/zrb#86]
Hi there,

Any plan to format the code using [black](https://github.com/psf/black)?

Pros:
* standardized format/style
* hopefully will make more people more comfortable reading the code

Cons:
* opinionated

**Comment by za** [comment]
Oups, should I use _ideas_ on _discussions_ instead? https://github.com/state-alchemists/zrb/discussions/categories/ideas

**Comment by goFrendiAsgard** [comment]
Hello @za thank you for starting the discussion.
Currently, we use flake8 for lining. What are some features in black that you missing for in Zrb codebase?

**Comment by za** [comment]
Do you mean _linting_ @goFrendiAsgard ? 

Well, black breaking multiple modules import into several lines, replace single-quote with double-quotes, etc.

I can initiate a PR so we can see _the diff_.

**Comment by goFrendiAsgard** [comment]
Nice, go for it @za 🚀🚀🚀

**Comment by za** [comment]
Any comment regarding the PR kak Go @goFrendiAsgard ? 

It's a big changes if we see the number of files that are being changed.

**Comment by goFrendiAsgard** [comment]
Looks good to me. All style changes looks good.
I have merged the PR as well.
Thank you @za, I will use black for Zrb default formatting.

**Comment by za** [comment]
_Matur nuwun_ kak @goFrendiAsgard for merging the PR 🥳
